// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

import * as borsh from '@coral-xyz/borsh';
import { PublicKey } from '@solana/web3.js';

export interface Player {
  wallet: PublicKey;
  username: string;
  level: number;
  experience: number;
  gold: number;
  health: number;
  mana: number;
  equipped_weapon?: PublicKey | undefined;
  equipped_armor?: PublicKey | undefined;
  equipped_accessory?: PublicKey | undefined;
  total_items_owned: number;
  total_monsters_defeated: number;
  created_at: number;
  last_login: number;
}

export const PlayerSchema = borsh.struct([
  borsh.publicKey('wallet'),
  borsh.string('username'),
  borsh.u16('level'),
  borsh.u64('experience'),
  borsh.u64('gold'),
  borsh.u32('health'),
  borsh.u32('mana'),
  borsh.option(borsh.publicKey)('equipped_weapon'),
  borsh.option(borsh.publicKey)('equipped_armor'),
  borsh.option(borsh.publicKey)('equipped_accessory'),
  borsh.u64('total_items_owned'),
  borsh.u64('total_monsters_defeated'),
  borsh.i64('created_at'),
  borsh.i64('last_login'),
]);


export interface GameItem {
  id: number;
  owner: PublicKey;
  name: string;
  item_type: ItemType;
  rarity: Rarity;
  level_requirement: number;
  power: number;
  defense: number;
  durability: number;
  max_durability: number;
  is_equipped: boolean;
  is_tradeable: boolean;
  created_at: number;
}

export const GameItemSchema = borsh.struct([
  borsh.u64('id'),
  borsh.publicKey('owner'),
  borsh.string('name'),
  borsh.itemtype('item_type'),
  borsh.rarity('rarity'),
  borsh.u16('level_requirement'),
  borsh.u32('power'),
  borsh.u32('defense'),
  borsh.u32('durability'),
  borsh.u32('max_durability'),
  borsh.bool('is_equipped'),
  borsh.bool('is_tradeable'),
  borsh.i64('created_at'),
]);


export type ItemType =
  | { kind: 'Weapon'; damage: number; attack_speed: number }
  | { kind: 'Armor'; defense_bonus: number; health_bonus: number }
  | { kind: 'Accessory'; mana_bonus: number; luck_bonus: number }
  | { kind: 'Consumable'; effect: ConsumableEffect; uses: number }
  | { kind: 'Material'; tier: number }
;

export const ItemTypeSchema = borsh.rustEnum([
  borsh.struct([
    borsh.u32('damage'),
    borsh.u32('attack_speed'),
  ], 'Weapon'),
  borsh.struct([
    borsh.u32('defense_bonus'),
    borsh.u32('health_bonus'),
  ], 'Armor'),
  borsh.struct([
    borsh.u32('mana_bonus'),
    borsh.u32('luck_bonus'),
  ], 'Accessory'),
  borsh.struct([
    borsh.consumableeffect('effect'),
    borsh.u32('uses'),
  ], 'Consumable'),
  borsh.struct([
    borsh.u8('tier'),
  ], 'Material'),
]);


export type ConsumableEffect =
  | { kind: 'HealHealth'; amount: number }
  | { kind: 'RestoreMana'; amount: number }
  | { kind: 'BoostExperience'; percentage: number; duration: number }
  | { kind: 'IncreaseGold'; percentage: number; duration: number }
;

export const ConsumableEffectSchema = borsh.rustEnum([
  borsh.struct([
    borsh.u32('amount'),
  ], 'HealHealth'),
  borsh.struct([
    borsh.u32('amount'),
  ], 'RestoreMana'),
  borsh.struct([
    borsh.u32('percentage'),
    borsh.i64('duration'),
  ], 'BoostExperience'),
  borsh.struct([
    borsh.u32('percentage'),
    borsh.i64('duration'),
  ], 'IncreaseGold'),
]);


export type Rarity =
  | { kind: 'Common' }
  | { kind: 'Uncommon' }
  | { kind: 'Rare' }
  | { kind: 'Epic' }
  | { kind: 'Legendary' }
  | { kind: 'Mythic' }
;

export const RaritySchema = borsh.rustEnum([
  borsh.unit('Common'),
  borsh.unit('Uncommon'),
  borsh.unit('Rare'),
  borsh.unit('Epic'),
  borsh.unit('Legendary'),
  borsh.unit('Mythic'),
]);


export interface CraftingRecipe {
  id: number;
  name: string;
  result_item_type: ItemType;
  result_rarity: Rarity;
  result_power: number;
  required_level: number;
  required_materials: Vec;
  crafting_cost: number;
  success_rate: number;
}

export const CraftingRecipeSchema = borsh.struct([
  borsh.u64('id'),
  borsh.string('name'),
  borsh.itemtype('result_item_type'),
  borsh.rarity('result_rarity'),
  borsh.u32('result_power'),
  borsh.u16('required_level'),
  borsh.vec('required_materials'),
  borsh.u64('crafting_cost'),
  borsh.u8('success_rate'),
]);


export interface MaterialRequirement {
  material_tier: number;
  quantity: number;
}

export const MaterialRequirementSchema = borsh.struct([
  borsh.u8('material_tier'),
  borsh.u32('quantity'),
]);


export interface TradeOffer {
  id: number;
  offerer: PublicKey;
  offered_item: PublicKey;
  requested_gold?: number | undefined;
  requested_item_type?: ItemType | undefined;
  requested_min_rarity?: Rarity | undefined;
  recipient?: PublicKey | undefined;
  status: TradeStatus;
  created_at: number;
  expires_at: number;
}

export const TradeOfferSchema = borsh.struct([
  borsh.u64('id'),
  borsh.publicKey('offerer'),
  borsh.publicKey('offered_item'),
  borsh.option(borsh.u64)('requested_gold'),
  borsh.option(borsh.itemtype)('requested_item_type'),
  borsh.option(borsh.rarity)('requested_min_rarity'),
  borsh.option(borsh.publicKey)('recipient'),
  borsh.tradestatus('status'),
  borsh.i64('created_at'),
  borsh.i64('expires_at'),
]);


export type TradeStatus =
  | { kind: 'Open' }
  | { kind: 'Accepted' }
  | { kind: 'Cancelled' }
  | { kind: 'Expired' }
;

export const TradeStatusSchema = borsh.rustEnum([
  borsh.unit('Open'),
  borsh.unit('Accepted'),
  borsh.unit('Cancelled'),
  borsh.unit('Expired'),
]);


export interface Achievement {
  player: PublicKey;
  achievement_type: AchievementType;
  unlocked_at: number;
  reward_claimed: boolean;
}

export const AchievementSchema = borsh.struct([
  borsh.publicKey('player'),
  borsh.achievementtype('achievement_type'),
  borsh.i64('unlocked_at'),
  borsh.bool('reward_claimed'),
]);


export type AchievementType =
  | { kind: 'ReachLevel'; level: number }
  | { kind: 'DefeatMonsters'; count: number }
  | { kind: 'CollectItems'; rarity: Rarity; count: number }
  | { kind: 'EarnGold'; amount: number }
  | { kind: 'CraftItems'; count: number }
  | { kind: 'CompleteTrades'; count: number }
;

export const AchievementTypeSchema = borsh.rustEnum([
  borsh.struct([
    borsh.u16('level'),
  ], 'ReachLevel'),
  borsh.struct([
    borsh.u64('count'),
  ], 'DefeatMonsters'),
  borsh.struct([
    borsh.rarity('rarity'),
    borsh.u64('count'),
  ], 'CollectItems'),
  borsh.struct([
    borsh.u64('amount'),
  ], 'EarnGold'),
  borsh.struct([
    borsh.u64('count'),
  ], 'CraftItems'),
  borsh.struct([
    borsh.u64('count'),
  ], 'CompleteTrades'),
]);


export interface GameEvent {
  event_type: EventType;
  player: PublicKey;
  timestamp: number;
  block_height: number;
}

export const GameEventSchema = borsh.struct([
  borsh.eventtype('event_type'),
  borsh.publicKey('player'),
  borsh.i64('timestamp'),
  borsh.u64('block_height'),
]);


export type EventType =
  | { kind: 'PlayerCreated' }
  | { kind: 'ItemMinted'; item_id: number; rarity: Rarity }
  | { kind: 'ItemEquipped'; item_id: number }
  | { kind: 'ItemUnequipped'; item_id: number }
  | { kind: 'ItemCrafted'; item_id: number; recipe_id: number }
  | { kind: 'ItemUpgraded'; item_id: number; new_power: number }
  | { kind: 'ItemConsumed'; item_id: number; effect: ConsumableEffect }
  | { kind: 'TradeCreated'; trade_id: number }
  | { kind: 'TradeCompleted'; trade_id: number; partner: PublicKey }
  | { kind: 'MonsterDefeated'; monster_type: string; gold_earned: number; exp_earned: number }
  | { kind: 'LevelUp'; new_level: number }
  | { kind: 'AchievementUnlocked'; achievement_type: AchievementType }
;

export const EventTypeSchema = borsh.rustEnum([
  borsh.unit('PlayerCreated'),
  borsh.struct([
    borsh.u64('item_id'),
    borsh.rarity('rarity'),
  ], 'ItemMinted'),
  borsh.struct([
    borsh.u64('item_id'),
  ], 'ItemEquipped'),
  borsh.struct([
    borsh.u64('item_id'),
  ], 'ItemUnequipped'),
  borsh.struct([
    borsh.u64('item_id'),
    borsh.u64('recipe_id'),
  ], 'ItemCrafted'),
  borsh.struct([
    borsh.u64('item_id'),
    borsh.u32('new_power'),
  ], 'ItemUpgraded'),
  borsh.struct([
    borsh.u64('item_id'),
    borsh.consumableeffect('effect'),
  ], 'ItemConsumed'),
  borsh.struct([
    borsh.u64('trade_id'),
  ], 'TradeCreated'),
  borsh.struct([
    borsh.u64('trade_id'),
    borsh.publicKey('partner'),
  ], 'TradeCompleted'),
  borsh.struct([
    borsh.string('monster_type'),
    borsh.u64('gold_earned'),
    borsh.u64('exp_earned'),
  ], 'MonsterDefeated'),
  borsh.struct([
    borsh.u16('new_level'),
  ], 'LevelUp'),
  borsh.struct([
    borsh.achievementtype('achievement_type'),
  ], 'AchievementUnlocked'),
]);


export interface GameStats {
  total_players: number;
  total_items_minted: number;
  total_trades_completed: number;
  total_items_crafted: number;
  total_gold_circulating: number;
  most_valuable_item?: PublicKey | undefined;
  highest_level_player?: PublicKey | undefined;
  last_updated: number;
}

export const GameStatsSchema = borsh.struct([
  borsh.u64('total_players'),
  borsh.u64('total_items_minted'),
  borsh.u64('total_trades_completed'),
  borsh.u64('total_items_crafted'),
  borsh.u64('total_gold_circulating'),
  borsh.option(borsh.publicKey)('most_valuable_item'),
  borsh.option(borsh.publicKey)('highest_level_player'),
  borsh.i64('last_updated'),
]);
