// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

import * as borsh from '@coral-xyz/borsh';
import { PublicKey } from '@solana/web3.js';

export interface VestingPool {
  authority: PublicKey;
  token_mint: PublicKey;
  vault: PublicKey;
  name: string;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_schedules: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_allocated: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_released: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_revoked: number;
  is_active: boolean;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  created_at: number;
}

export const VestingPoolSchema = borsh.struct([
  borsh.publicKey('authority'),
  borsh.publicKey('token_mint'),
  borsh.publicKey('vault'),
  borsh.string('name'),
  borsh.u64('total_schedules'),
  borsh.u64('total_allocated'),
  borsh.u64('total_released'),
  borsh.u64('total_revoked'),
  borsh.bool('is_active'),
  borsh.i64('created_at'),
]);


export interface VestingSchedule {
  pool: PublicKey;
  beneficiary: PublicKey;
  vesting_type: VestingType;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_amount: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  released_amount: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  start_time: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  end_time: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  cliff_time?: number | undefined;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  last_release_time: number;
  is_revocable: boolean;
  is_revoked: boolean;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  revoked_at?: number | undefined;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  created_at: number;
}

export const VestingScheduleSchema = borsh.struct([
  borsh.publicKey('pool'),
  borsh.publicKey('beneficiary'),
  VestingTypeSchema('vesting_type'),
  borsh.u64('total_amount'),
  borsh.u64('released_amount'),
  borsh.i64('start_time'),
  borsh.i64('end_time'),
  borsh.option(borsh.i64)('cliff_time'),
  borsh.i64('last_release_time'),
  borsh.bool('is_revocable'),
  borsh.bool('is_revoked'),
  borsh.option(borsh.i64)('revoked_at'),
  borsh.i64('created_at'),
]);


/**
 * WARNING: Some variants contain TypeScript 'number' types with precision limit of 2^53-1.
 * Large values (e.g., Solana lamports) may lose precision during serialization.
 */
export type VestingType =
  | { kind: 'Linear' }
  | { kind: 'Cliff'; cliff_duration: number }
  | { kind: 'CliffLinear'; cliff_duration: number; cliff_percentage: number }
  | { kind: 'Milestone'; milestones: Milestone[] }
;

export const VestingTypeSchema = borsh.rustEnum([
  borsh.unit('Linear'),
  borsh.struct([
    borsh.i64('cliff_duration'),
  ], 'Cliff'),
  borsh.struct([
    borsh.i64('cliff_duration'),
    borsh.u64('cliff_percentage'),
  ], 'CliffLinear'),
  borsh.struct([
    borsh.vec(MilestoneSchema)('milestones'),
  ], 'Milestone'),
]);


export interface Milestone {
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  unlock_time: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  percentage: number;
  is_unlocked: boolean;
}

export const MilestoneSchema = borsh.struct([
  borsh.i64('unlock_time'),
  borsh.u64('percentage'),
  borsh.bool('is_unlocked'),
]);


export interface ReleaseRecord {
  schedule: PublicKey;
  beneficiary: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  amount: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  released_at: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  cumulative_released: number;
}

export const ReleaseRecordSchema = borsh.struct([
  borsh.publicKey('schedule'),
  borsh.publicKey('beneficiary'),
  borsh.u64('amount'),
  borsh.i64('released_at'),
  borsh.u64('cumulative_released'),
]);


export interface Beneficiary {
  wallet: PublicKey;
  pool: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_allocated: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_released: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_revoked: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  schedules_count: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  first_vesting_at: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  last_release_at: number;
}

export const BeneficiarySchema = borsh.struct([
  borsh.publicKey('wallet'),
  borsh.publicKey('pool'),
  borsh.u64('total_allocated'),
  borsh.u64('total_released'),
  borsh.u64('total_revoked'),
  borsh.u64('schedules_count'),
  borsh.i64('first_vesting_at'),
  borsh.i64('last_release_at'),
]);


export interface RevocationRecord {
  schedule: PublicKey;
  beneficiary: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  amount_vested: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  amount_revoked: number;
  revoked_by: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  revoked_at: number;
  reason: string;
}

export const RevocationRecordSchema = borsh.struct([
  borsh.publicKey('schedule'),
  borsh.publicKey('beneficiary'),
  borsh.u64('amount_vested'),
  borsh.u64('amount_revoked'),
  borsh.publicKey('revoked_by'),
  borsh.i64('revoked_at'),
  borsh.string('reason'),
]);


export interface VestingEvent {
  event_type: EventType;
  pool: PublicKey;
  beneficiary: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  amount: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  timestamp: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  block_height: number;
}

export const VestingEventSchema = borsh.struct([
  EventTypeSchema('event_type'),
  borsh.publicKey('pool'),
  borsh.publicKey('beneficiary'),
  borsh.u64('amount'),
  borsh.i64('timestamp'),
  borsh.u64('block_height'),
]);


/**
 * WARNING: Some variants contain TypeScript 'number' types with precision limit of 2^53-1.
 * Large values (e.g., Solana lamports) may lose precision during serialization.
 */
export type EventType =
  | { kind: 'PoolCreated' }
  | { kind: 'ScheduleCreated'; schedule_id: PublicKey; vesting_type: VestingType; total_amount: number }
  | { kind: 'TokensReleased'; schedule_id: PublicKey; amount: number }
  | { kind: 'ScheduleRevoked'; schedule_id: PublicKey; amount_revoked: number }
  | { kind: 'MilestoneUnlocked'; schedule_id: PublicKey; milestone_index: number }
  | { kind: 'BeneficiaryUpdated'; old_beneficiary: PublicKey; new_beneficiary: PublicKey }
;

export const EventTypeSchema = borsh.rustEnum([
  borsh.unit('PoolCreated'),
  borsh.struct([
    borsh.publicKey('schedule_id'),
    VestingTypeSchema('vesting_type'),
    borsh.u64('total_amount'),
  ], 'ScheduleCreated'),
  borsh.struct([
    borsh.publicKey('schedule_id'),
    borsh.u64('amount'),
  ], 'TokensReleased'),
  borsh.struct([
    borsh.publicKey('schedule_id'),
    borsh.u64('amount_revoked'),
  ], 'ScheduleRevoked'),
  borsh.struct([
    borsh.publicKey('schedule_id'),
    borsh.u64('milestone_index'),
  ], 'MilestoneUnlocked'),
  borsh.struct([
    borsh.publicKey('old_beneficiary'),
    borsh.publicKey('new_beneficiary'),
  ], 'BeneficiaryUpdated'),
]);


export interface PoolStats {
  pool: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_beneficiaries: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  average_vesting_duration: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  largest_allocation: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_cliffs_passed: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_milestones_unlocked: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  completion_rate: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  last_updated: number;
}

export const PoolStatsSchema = borsh.struct([
  borsh.publicKey('pool'),
  borsh.u64('total_beneficiaries'),
  borsh.i64('average_vesting_duration'),
  borsh.u64('largest_allocation'),
  borsh.u64('total_cliffs_passed'),
  borsh.u64('total_milestones_unlocked'),
  borsh.u64('completion_rate'),
  borsh.i64('last_updated'),
]);


export interface BeneficiaryStats {
  beneficiary: PublicKey;
  pool: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  vesting_progress: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  days_until_next_release: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  estimated_monthly_release: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_schedules_completed: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  average_release_interval: number;
}

export const BeneficiaryStatsSchema = borsh.struct([
  borsh.publicKey('beneficiary'),
  borsh.publicKey('pool'),
  borsh.u64('vesting_progress'),
  borsh.i64('days_until_next_release'),
  borsh.u64('estimated_monthly_release'),
  borsh.u64('total_schedules_completed'),
  borsh.i64('average_release_interval'),
]);
