// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

import * as borsh from '@coral-xyz/borsh';
import { PublicKey } from '@solana/web3.js';

export interface MarketplaceConfig {
  authority: PublicKey;
  fee_percentage: number;
  treasury: PublicKey;
  total_sales: number;
  is_paused: boolean;
}

export const MarketplaceConfigSchema = borsh.struct([
  borsh.publicKey('authority'),
  borsh.u16('fee_percentage'),
  borsh.publicKey('treasury'),
  borsh.u64('total_sales'),
  borsh.bool('is_paused'),
]);


export interface Listing {
  seller: PublicKey;
  nft_mint: PublicKey;
  price: number;
  listed_at: number;
  status: ListingStatus;
  buyer?: PublicKey | undefined;
  sold_at?: number | undefined;
}

export const ListingSchema = borsh.struct([
  borsh.publicKey('seller'),
  borsh.publicKey('nft_mint'),
  borsh.u64('price'),
  borsh.i64('listed_at'),
  borsh.listingstatus('status'),
  borsh.option(borsh.publicKey)('buyer'),
  borsh.option(borsh.i64)('sold_at'),
]);


export type ListingStatus =
  | { kind: 'Active' }
  | { kind: 'Sold' }
  | { kind: 'Cancelled' }
;

export const ListingStatusSchema = borsh.rustEnum([
  borsh.unit('Active'),
  borsh.unit('Sold'),
  borsh.unit('Cancelled'),
]);


export interface NFTMetadata {
  name: string;
  symbol: string;
  uri: string;
  creator: PublicKey;
  collection?: PublicKey | undefined;
  royalty_percentage: number;
}

export const NFTMetadataSchema = borsh.struct([
  borsh.string('name'),
  borsh.string('symbol'),
  borsh.string('uri'),
  borsh.publicKey('creator'),
  borsh.option(borsh.publicKey)('collection'),
  borsh.u16('royalty_percentage'),
]);


export interface TransactionRecord {
  transaction_type: TransactionType;
  nft_mint: PublicKey;
  from: PublicKey;
  to: PublicKey;
  price: number;
  timestamp: number;
}

export const TransactionRecordSchema = borsh.struct([
  borsh.transactiontype('transaction_type'),
  borsh.publicKey('nft_mint'),
  borsh.publicKey('from'),
  borsh.publicKey('to'),
  borsh.u64('price'),
  borsh.i64('timestamp'),
]);


export type TransactionType =
  | { kind: 'Listed' }
  | { kind: 'Sold' }
  | { kind: 'Cancelled' }
  | { kind: 'PriceUpdated'; old_price: number; new_price: number }
;

export const TransactionTypeSchema = borsh.rustEnum([
  borsh.unit('Listed'),
  borsh.unit('Sold'),
  borsh.unit('Cancelled'),
  borsh.struct([
    borsh.u64('old_price'),
    borsh.u64('new_price'),
  ], 'PriceUpdated'),
]);


export interface UserProfile {
  owner: PublicKey;
  total_listed: number;
  total_sold: number;
  total_purchased: number;
  joined_at: number;
}

export const UserProfileSchema = borsh.struct([
  borsh.publicKey('owner'),
  borsh.u64('total_listed'),
  borsh.u64('total_sold'),
  borsh.u64('total_purchased'),
  borsh.i64('joined_at'),
]);
