// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

import * as borsh from '@coral-xyz/borsh';
import { PublicKey } from '@solana/web3.js';

export interface DAO {
  authority: PublicKey;
  name: string;
  treasury: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_members: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_proposals: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  voting_period: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  timelock_delay: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  quorum_threshold: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  approval_threshold: number;
  is_active: boolean;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  created_at: number;
}

export const DAOSchema = borsh.struct([
  borsh.publicKey('authority'),
  borsh.string('name'),
  borsh.publicKey('treasury'),
  borsh.u64('total_members'),
  borsh.u64('total_proposals'),
  borsh.i64('voting_period'),
  borsh.i64('timelock_delay'),
  borsh.u64('quorum_threshold'),
  borsh.u64('approval_threshold'),
  borsh.bool('is_active'),
  borsh.i64('created_at'),
]);


export interface Proposal {
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  id: number;
  dao: PublicKey;
  proposer: PublicKey;
  title: string;
  description: string;
  proposal_type: ProposalType;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  yes_votes: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  no_votes: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  abstain_votes: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_votes: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  start_time: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  end_time: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  queued_at?: number | undefined;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  executed_at?: number | undefined;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  cancelled_at?: number | undefined;
  status: ProposalStatus;
}

export const ProposalSchema = borsh.struct([
  borsh.u64('id'),
  borsh.publicKey('dao'),
  borsh.publicKey('proposer'),
  borsh.string('title'),
  borsh.string('description'),
  ProposalTypeSchema('proposal_type'),
  borsh.u64('yes_votes'),
  borsh.u64('no_votes'),
  borsh.u64('abstain_votes'),
  borsh.u64('total_votes'),
  borsh.i64('start_time'),
  borsh.i64('end_time'),
  borsh.option(borsh.i64)('queued_at'),
  borsh.option(borsh.i64)('executed_at'),
  borsh.option(borsh.i64)('cancelled_at'),
  ProposalStatusSchema('status'),
]);


/**
 * WARNING: Some variants contain TypeScript 'number' types with precision limit of 2^53-1.
 * Large values (e.g., Solana lamports) may lose precision during serialization.
 */
export type ProposalType =
  | { kind: 'Transfer'; recipient: PublicKey; amount: number }
  | { kind: 'ConfigChange'; voting_period: number | undefined; timelock_delay: number | undefined; quorum_threshold: number | undefined; approval_threshold: number | undefined }
  | { kind: 'AddMember'; member: PublicKey; voting_power: number }
  | { kind: 'RemoveMember'; member: PublicKey }
  | { kind: 'Custom'; instruction_data: string; target_program: PublicKey }
;

export const ProposalTypeSchema = borsh.rustEnum([
  borsh.struct([
    borsh.publicKey('recipient'),
    borsh.u64('amount'),
  ], 'Transfer'),
  borsh.struct([
    borsh.option(borsh.i64)('voting_period'),
    borsh.option(borsh.i64)('timelock_delay'),
    borsh.option(borsh.u64)('quorum_threshold'),
    borsh.option(borsh.u64)('approval_threshold'),
  ], 'ConfigChange'),
  borsh.struct([
    borsh.publicKey('member'),
    borsh.u64('voting_power'),
  ], 'AddMember'),
  borsh.struct([
    borsh.publicKey('member'),
  ], 'RemoveMember'),
  borsh.struct([
    borsh.string('instruction_data'),
    borsh.publicKey('target_program'),
  ], 'Custom'),
]);


export type ProposalStatus =
  | { kind: 'Draft' }
  | { kind: 'Active' }
  | { kind: 'Succeeded' }
  | { kind: 'Defeated' }
  | { kind: 'Queued' }
  | { kind: 'Executed' }
  | { kind: 'Cancelled' }
  | { kind: 'Expired' }
;

export const ProposalStatusSchema = borsh.rustEnum([
  borsh.unit('Draft'),
  borsh.unit('Active'),
  borsh.unit('Succeeded'),
  borsh.unit('Defeated'),
  borsh.unit('Queued'),
  borsh.unit('Executed'),
  borsh.unit('Cancelled'),
  borsh.unit('Expired'),
]);


export interface Vote {
  proposal: PublicKey;
  voter: PublicKey;
  vote_type: VoteType;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  voting_power: number;
  comment: string;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  voted_at: number;
}

export const VoteSchema = borsh.struct([
  borsh.publicKey('proposal'),
  borsh.publicKey('voter'),
  VoteTypeSchema('vote_type'),
  borsh.u64('voting_power'),
  borsh.string('comment'),
  borsh.i64('voted_at'),
]);


export type VoteType =
  | { kind: 'Yes' }
  | { kind: 'No' }
  | { kind: 'Abstain' }
;

export const VoteTypeSchema = borsh.rustEnum([
  borsh.unit('Yes'),
  borsh.unit('No'),
  borsh.unit('Abstain'),
]);


export interface Member {
  dao: PublicKey;
  wallet: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  voting_power: number;
  delegate?: PublicKey | undefined;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  proposals_created: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  votes_cast: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  joined_at: number;
  is_active: boolean;
}

export const MemberSchema = borsh.struct([
  borsh.publicKey('dao'),
  borsh.publicKey('wallet'),
  borsh.u64('voting_power'),
  borsh.option(borsh.publicKey)('delegate'),
  borsh.u64('proposals_created'),
  borsh.u64('votes_cast'),
  borsh.i64('joined_at'),
  borsh.bool('is_active'),
]);


export interface VoteDelegation {
  delegator: PublicKey;
  delegatee: PublicKey;
  dao: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  delegated_power: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  created_at: number;
}

export const VoteDelegationSchema = borsh.struct([
  borsh.publicKey('delegator'),
  borsh.publicKey('delegatee'),
  borsh.publicKey('dao'),
  borsh.u64('delegated_power'),
  borsh.i64('created_at'),
]);


export interface GovernanceEvent {
  event_type: EventType;
  dao: PublicKey;
  actor: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  timestamp: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  block_height: number;
}

export const GovernanceEventSchema = borsh.struct([
  EventTypeSchema('event_type'),
  borsh.publicKey('dao'),
  borsh.publicKey('actor'),
  borsh.i64('timestamp'),
  borsh.u64('block_height'),
]);


/**
 * WARNING: Some variants contain TypeScript 'number' types with precision limit of 2^53-1.
 * Large values (e.g., Solana lamports) may lose precision during serialization.
 */
export type EventType =
  | { kind: 'DAOCreated' }
  | { kind: 'ProposalCreated'; proposal_id: number }
  | { kind: 'VoteCast'; proposal_id: number; vote_type: VoteType }
  | { kind: 'ProposalQueued'; proposal_id: number }
  | { kind: 'ProposalExecuted'; proposal_id: number }
  | { kind: 'ProposalCancelled'; proposal_id: number }
  | { kind: 'MemberAdded'; member: PublicKey }
  | { kind: 'MemberRemoved'; member: PublicKey }
  | { kind: 'VoteDelegated'; from: PublicKey; to: PublicKey }
  | { kind: 'ConfigChanged' }
;

export const EventTypeSchema = borsh.rustEnum([
  borsh.unit('DAOCreated'),
  borsh.struct([
    borsh.u64('proposal_id'),
  ], 'ProposalCreated'),
  borsh.struct([
    borsh.u64('proposal_id'),
    VoteTypeSchema('vote_type'),
  ], 'VoteCast'),
  borsh.struct([
    borsh.u64('proposal_id'),
  ], 'ProposalQueued'),
  borsh.struct([
    borsh.u64('proposal_id'),
  ], 'ProposalExecuted'),
  borsh.struct([
    borsh.u64('proposal_id'),
  ], 'ProposalCancelled'),
  borsh.struct([
    borsh.publicKey('member'),
  ], 'MemberAdded'),
  borsh.struct([
    borsh.publicKey('member'),
  ], 'MemberRemoved'),
  borsh.struct([
    borsh.publicKey('from'),
    borsh.publicKey('to'),
  ], 'VoteDelegated'),
  borsh.unit('ConfigChanged'),
]);


export interface DAOStats {
  dao: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_votes_cast: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_proposals_passed: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_proposals_failed: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_treasury_spent: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  average_participation_rate: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  last_activity_at: number;
}

export const DAOStatsSchema = borsh.struct([
  borsh.publicKey('dao'),
  borsh.u64('total_votes_cast'),
  borsh.u64('total_proposals_passed'),
  borsh.u64('total_proposals_failed'),
  borsh.u64('total_treasury_spent'),
  borsh.u64('average_participation_rate'),
  borsh.i64('last_activity_at'),
]);


export interface MemberStats {
  member: PublicKey;
  dao: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_proposals_created: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_votes_cast: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  proposals_passed: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  proposals_failed: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  voting_power_received: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  voting_power_delegated: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  participation_rate: number;
}

export const MemberStatsSchema = borsh.struct([
  borsh.publicKey('member'),
  borsh.publicKey('dao'),
  borsh.u64('total_proposals_created'),
  borsh.u64('total_votes_cast'),
  borsh.u64('proposals_passed'),
  borsh.u64('proposals_failed'),
  borsh.u64('voting_power_received'),
  borsh.u64('voting_power_delegated'),
  borsh.u64('participation_rate'),
]);
