// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

use anchor_lang::prelude::*;
use solana_program::pubkey::Pubkey;

#[account]
pub struct DAO {
    pub authority: Pubkey,
    pub name: String,
    pub treasury: Pubkey,
    pub total_members: u64,
    pub total_proposals: u64,
    pub voting_period: i64,
    pub timelock_delay: i64,
    pub quorum_threshold: u64,
    pub approval_threshold: u64,
    pub is_active: bool,
    pub created_at: i64,
}

#[account]
pub struct Proposal {
    pub id: u64,
    pub dao: Pubkey,
    pub proposer: Pubkey,
    pub title: String,
    pub description: String,
    pub proposal_type: ProposalType,
    pub yes_votes: u64,
    pub no_votes: u64,
    pub abstain_votes: u64,
    pub total_votes: u64,
    pub start_time: i64,
    pub end_time: i64,
    pub queued_at: Option<i64>,
    pub executed_at: Option<i64>,
    pub cancelled_at: Option<i64>,
    pub status: ProposalStatus,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum ProposalType {
    Transfer {
        recipient: Pubkey,
        amount: u64,
    },
    ConfigChange {
        voting_period: Option<i64>,
        timelock_delay: Option<i64>,
        quorum_threshold: Option<u64>,
        approval_threshold: Option<u64>,
    },
    AddMember {
        member: Pubkey,
        voting_power: u64,
    },
    RemoveMember {
        member: Pubkey,
    },
    Custom {
        instruction_data: String,
        target_program: Pubkey,
    },
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum ProposalStatus {
    Draft,
    Active,
    Succeeded,
    Defeated,
    Queued,
    Executed,
    Cancelled,
    Expired,
}

#[account]
pub struct Vote {
    pub proposal: Pubkey,
    pub voter: Pubkey,
    pub vote_type: VoteType,
    pub voting_power: u64,
    pub comment: String,
    pub voted_at: i64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum VoteType {
    Yes,
    No,
    Abstain,
}

#[account]
pub struct Member {
    pub dao: Pubkey,
    pub wallet: Pubkey,
    pub voting_power: u64,
    pub delegate: Option<Pubkey>,
    pub proposals_created: u64,
    pub votes_cast: u64,
    pub joined_at: i64,
    pub is_active: bool,
}

#[account]
pub struct VoteDelegation {
    pub delegator: Pubkey,
    pub delegatee: Pubkey,
    pub dao: Pubkey,
    pub delegated_power: u64,
    pub created_at: i64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub struct GovernanceEvent {
    pub event_type: EventType,
    pub dao: Pubkey,
    pub actor: Pubkey,
    pub timestamp: i64,
    pub block_height: u64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum EventType {
    DAOCreated,
    ProposalCreated {
        proposal_id: u64,
    },
    VoteCast {
        proposal_id: u64,
        vote_type: VoteType,
    },
    ProposalQueued {
        proposal_id: u64,
    },
    ProposalExecuted {
        proposal_id: u64,
    },
    ProposalCancelled {
        proposal_id: u64,
    },
    MemberAdded {
        member: Pubkey,
    },
    MemberRemoved {
        member: Pubkey,
    },
    VoteDelegated {
        from: Pubkey,
        to: Pubkey,
    },
    ConfigChanged,
}

#[account]
pub struct DAOStats {
    pub dao: Pubkey,
    pub total_votes_cast: u64,
    pub total_proposals_passed: u64,
    pub total_proposals_failed: u64,
    pub total_treasury_spent: u64,
    pub average_participation_rate: u64,
    pub last_activity_at: i64,
}

#[account]
pub struct MemberStats {
    pub member: Pubkey,
    pub dao: Pubkey,
    pub total_proposals_created: u64,
    pub total_votes_cast: u64,
    pub proposals_passed: u64,
    pub proposals_failed: u64,
    pub voting_power_received: u64,
    pub voting_power_delegated: u64,
    pub participation_rate: u64,
}
