// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

use anchor_lang::prelude::*;

#[account]
pub struct StakingPool {
    pub authority: Pubkey,
    pub token_mint: Pubkey,
    pub vault: Pubkey,
    pub total_staked: u64,
    pub total_stakers: u64,
    pub reward_rate: u64,
    pub min_stake_amount: u64,
    pub min_lock_duration: i64,
    pub cooldown_period: i64,
    pub is_active: bool,
    pub created_at: i64,
}

#[account]
pub struct StakeAccount {
    pub owner: Pubkey,
    pub pool: Pubkey,
    pub amount: u64,
    pub staked_at: i64,
    pub last_claim_at: i64,
    pub unlock_at: i64,
    pub total_claimed: u64,
    pub status: StakingStatus,
    pub unstake_requested_at: Option<i64>,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum StakingStatus {
    Active,
    Locked,
    UnstakeRequested,
    Unstaked,
}

#[account]
pub struct RewardConfig {
    pub pool: Pubkey,
    pub calculation_type: RewardCalculationType,
    pub base_apy: u64,
    pub bonus_multiplier: u64,
    pub max_apy: u64,
    pub compound_frequency: i64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum RewardCalculationType {
    FixedAPY,
    TieredAPY {
        tier1_amount: u64,
        tier1_apy: u64,
        tier2_amount: u64,
        tier2_apy: u64,
        tier3_apy: u64,
    },
    DynamicAPY {
        min_apy: u64,
        max_apy: u64,
        utilization_threshold: u64,
    },
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub struct StakingEvent {
    pub event_type: EventType,
    pub user: Pubkey,
    pub pool: Pubkey,
    pub amount: u64,
    pub timestamp: i64,
    pub block_height: u64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum EventType {
    Staked,
    Unstaked,
    RewardClaimed {
        reward_amount: u64,
    },
    UnstakeRequested,
    EmergencyWithdraw {
        penalty: u64,
    },
    LockExtended {
        new_unlock_time: i64,
    },
}

#[account]
pub struct UserStakingStats {
    pub owner: Pubkey,
    pub total_staked_lifetime: u64,
    pub total_rewards_claimed: u64,
    pub total_pools_participated: u64,
    pub first_stake_at: i64,
    pub last_activity_at: i64,
}

#[account]
pub struct PoolStats {
    pub pool: Pubkey,
    pub total_rewards_distributed: u64,
    pub average_stake_duration: i64,
    pub highest_stake: u64,
    pub current_apy: u64,
    pub last_updated: i64,
}
