// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

use anchor_lang::prelude::*;

#[account]
pub struct MarketplaceConfig {
    pub authority: Pubkey,
    pub fee_percentage: u16,
    pub treasury: Pubkey,
    pub total_sales: u64,
    pub is_paused: bool,
}

#[account]
pub struct Listing {
    pub seller: Pubkey,
    pub nft_mint: Pubkey,
    pub price: u64,
    pub listed_at: i64,
    pub status: ListingStatus,
    pub buyer: Option<Pubkey>,
    pub sold_at: Option<i64>,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum ListingStatus {
    Active,
    Sold,
    Cancelled,
}

#[account]
pub struct NFTMetadata {
    pub name: String,
    pub symbol: String,
    pub uri: String,
    pub creator: Pubkey,
    pub collection: Option<Pubkey>,
    pub royalty_percentage: u16,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub struct TransactionRecord {
    pub transaction_type: TransactionType,
    pub nft_mint: Pubkey,
    pub from: Pubkey,
    pub to: Pubkey,
    pub price: u64,
    pub timestamp: i64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum TransactionType {
    Listed,
    Sold,
    Cancelled,
    PriceUpdated {
        old_price: u64,
        new_price: u64,
    },
}

#[account]
pub struct UserProfile {
    pub owner: Pubkey,
    pub total_listed: u64,
    pub total_sold: u64,
    pub total_purchased: u64,
    pub joined_at: i64,
}
