// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

use anchor_lang::prelude::*;

#[account]
pub struct VestingPool {
    pub authority: Pubkey,
    pub token_mint: Pubkey,
    pub vault: Pubkey,
    pub name: String,
    pub total_schedules: u64,
    pub total_allocated: u64,
    pub total_released: u64,
    pub total_revoked: u64,
    pub is_active: bool,
    pub created_at: i64,
}

#[account]
pub struct VestingSchedule {
    pub pool: Pubkey,
    pub beneficiary: Pubkey,
    pub vesting_type: VestingType,
    pub total_amount: u64,
    pub released_amount: u64,
    pub start_time: i64,
    pub end_time: i64,
    pub cliff_time: Option<i64>,
    pub last_release_time: i64,
    pub is_revocable: bool,
    pub is_revoked: bool,
    pub revoked_at: Option<i64>,
    pub created_at: i64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum VestingType {
    Linear,
    Cliff {
        cliff_duration: i64,
    },
    CliffLinear {
        cliff_duration: i64,
        cliff_percentage: u64,
    },
    Milestone {
        milestones: Vec<Milestone>,
    },
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub struct Milestone {
    pub unlock_time: i64,
    pub percentage: u64,
    pub is_unlocked: bool,
}

#[account]
pub struct ReleaseRecord {
    pub schedule: Pubkey,
    pub beneficiary: Pubkey,
    pub amount: u64,
    pub released_at: i64,
    pub cumulative_released: u64,
}

#[account]
pub struct Beneficiary {
    pub wallet: Pubkey,
    pub pool: Pubkey,
    pub total_allocated: u64,
    pub total_released: u64,
    pub total_revoked: u64,
    pub schedules_count: u64,
    pub first_vesting_at: i64,
    pub last_release_at: i64,
}

#[account]
pub struct RevocationRecord {
    pub schedule: Pubkey,
    pub beneficiary: Pubkey,
    pub amount_vested: u64,
    pub amount_revoked: u64,
    pub revoked_by: Pubkey,
    pub revoked_at: i64,
    pub reason: String,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub struct VestingEvent {
    pub event_type: EventType,
    pub pool: Pubkey,
    pub beneficiary: Pubkey,
    pub amount: u64,
    pub timestamp: i64,
    pub block_height: u64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum EventType {
    PoolCreated,
    ScheduleCreated {
        schedule_id: Pubkey,
        vesting_type: VestingType,
        total_amount: u64,
    },
    TokensReleased {
        schedule_id: Pubkey,
        amount: u64,
    },
    ScheduleRevoked {
        schedule_id: Pubkey,
        amount_revoked: u64,
    },
    MilestoneUnlocked {
        schedule_id: Pubkey,
        milestone_index: u64,
    },
    BeneficiaryUpdated {
        old_beneficiary: Pubkey,
        new_beneficiary: Pubkey,
    },
}

#[account]
pub struct PoolStats {
    pub pool: Pubkey,
    pub total_beneficiaries: u64,
    pub average_vesting_duration: i64,
    pub largest_allocation: u64,
    pub total_cliffs_passed: u64,
    pub total_milestones_unlocked: u64,
    pub completion_rate: u64,
    pub last_updated: i64,
}

#[account]
pub struct BeneficiaryStats {
    pub beneficiary: Pubkey,
    pub pool: Pubkey,
    pub vesting_progress: u64,
    pub days_until_next_release: i64,
    pub estimated_monthly_release: u64,
    pub total_schedules_completed: u64,
    pub average_release_interval: i64,
}
