// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

import * as borsh from '@coral-xyz/borsh';
import { PublicKey } from '@solana/web3.js';

export interface StakingPool {
  authority: PublicKey;
  token_mint: PublicKey;
  vault: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_staked: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_stakers: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  reward_rate: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  min_stake_amount: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  min_lock_duration: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  cooldown_period: number;
  is_active: boolean;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  created_at: number;
}

export const StakingPoolSchema = borsh.struct([
  borsh.publicKey('authority'),
  borsh.publicKey('token_mint'),
  borsh.publicKey('vault'),
  borsh.u64('total_staked'),
  borsh.u64('total_stakers'),
  borsh.u64('reward_rate'),
  borsh.u64('min_stake_amount'),
  borsh.i64('min_lock_duration'),
  borsh.i64('cooldown_period'),
  borsh.bool('is_active'),
  borsh.i64('created_at'),
]);


export interface StakeAccount {
  owner: PublicKey;
  pool: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  amount: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  staked_at: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  last_claim_at: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  unlock_at: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_claimed: number;
  status: StakingStatus;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  unstake_requested_at?: number | undefined;
}

export const StakeAccountSchema = borsh.struct([
  borsh.publicKey('owner'),
  borsh.publicKey('pool'),
  borsh.u64('amount'),
  borsh.i64('staked_at'),
  borsh.i64('last_claim_at'),
  borsh.i64('unlock_at'),
  borsh.u64('total_claimed'),
  StakingStatusSchema('status'),
  borsh.option(borsh.i64)('unstake_requested_at'),
]);


export type StakingStatus =
  | { kind: 'Active' }
  | { kind: 'Locked' }
  | { kind: 'UnstakeRequested' }
  | { kind: 'Unstaked' }
;

export const StakingStatusSchema = borsh.rustEnum([
  borsh.unit('Active'),
  borsh.unit('Locked'),
  borsh.unit('UnstakeRequested'),
  borsh.unit('Unstaked'),
]);


export interface RewardConfig {
  pool: PublicKey;
  calculation_type: RewardCalculationType;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  base_apy: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  bonus_multiplier: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  max_apy: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  compound_frequency: number;
}

export const RewardConfigSchema = borsh.struct([
  borsh.publicKey('pool'),
  RewardCalculationTypeSchema('calculation_type'),
  borsh.u64('base_apy'),
  borsh.u64('bonus_multiplier'),
  borsh.u64('max_apy'),
  borsh.i64('compound_frequency'),
]);


/**
 * WARNING: Some variants contain TypeScript 'number' types with precision limit of 2^53-1.
 * Large values (e.g., Solana lamports) may lose precision during serialization.
 */
export type RewardCalculationType =
  | { kind: 'FixedAPY' }
  | { kind: 'TieredAPY'; tier1_amount: number; tier1_apy: number; tier2_amount: number; tier2_apy: number; tier3_apy: number }
  | { kind: 'DynamicAPY'; min_apy: number; max_apy: number; utilization_threshold: number }
;

export const RewardCalculationTypeSchema = borsh.rustEnum([
  borsh.unit('FixedAPY'),
  borsh.struct([
    borsh.u64('tier1_amount'),
    borsh.u64('tier1_apy'),
    borsh.u64('tier2_amount'),
    borsh.u64('tier2_apy'),
    borsh.u64('tier3_apy'),
  ], 'TieredAPY'),
  borsh.struct([
    borsh.u64('min_apy'),
    borsh.u64('max_apy'),
    borsh.u64('utilization_threshold'),
  ], 'DynamicAPY'),
]);


export interface StakingEvent {
  event_type: EventType;
  user: PublicKey;
  pool: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  amount: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  timestamp: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  block_height: number;
}

export const StakingEventSchema = borsh.struct([
  EventTypeSchema('event_type'),
  borsh.publicKey('user'),
  borsh.publicKey('pool'),
  borsh.u64('amount'),
  borsh.i64('timestamp'),
  borsh.u64('block_height'),
]);


/**
 * WARNING: Some variants contain TypeScript 'number' types with precision limit of 2^53-1.
 * Large values (e.g., Solana lamports) may lose precision during serialization.
 */
export type EventType =
  | { kind: 'Staked' }
  | { kind: 'Unstaked' }
  | { kind: 'RewardClaimed'; reward_amount: number }
  | { kind: 'UnstakeRequested' }
  | { kind: 'EmergencyWithdraw'; penalty: number }
  | { kind: 'LockExtended'; new_unlock_time: number }
;

export const EventTypeSchema = borsh.rustEnum([
  borsh.unit('Staked'),
  borsh.unit('Unstaked'),
  borsh.struct([
    borsh.u64('reward_amount'),
  ], 'RewardClaimed'),
  borsh.unit('UnstakeRequested'),
  borsh.struct([
    borsh.u64('penalty'),
  ], 'EmergencyWithdraw'),
  borsh.struct([
    borsh.i64('new_unlock_time'),
  ], 'LockExtended'),
]);


export interface UserStakingStats {
  owner: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_staked_lifetime: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_rewards_claimed: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_pools_participated: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  first_stake_at: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  last_activity_at: number;
}

export const UserStakingStatsSchema = borsh.struct([
  borsh.publicKey('owner'),
  borsh.u64('total_staked_lifetime'),
  borsh.u64('total_rewards_claimed'),
  borsh.u64('total_pools_participated'),
  borsh.i64('first_stake_at'),
  borsh.i64('last_activity_at'),
]);


export interface PoolStats {
  pool: PublicKey;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  total_rewards_distributed: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  average_stake_duration: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  highest_stake: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  current_apy: number;
  /**
   * WARNING: TypeScript 'number' has precision limit of 2^53-1 (9,007,199,254,740,991).
   * For Solana lamports or large values, ensure they stay within safe range.
   * Values exceeding this limit will lose precision during serialization.
   */
  last_updated: number;
}

export const PoolStatsSchema = borsh.struct([
  borsh.publicKey('pool'),
  borsh.u64('total_rewards_distributed'),
  borsh.i64('average_stake_duration'),
  borsh.u64('highest_stake'),
  borsh.u64('current_apy'),
  borsh.i64('last_updated'),
]);
