// Auto-generated by LUMOS
// DO NOT EDIT - Changes will be overwritten

use anchor_lang::prelude::*;

#[account]
pub struct Player {
    pub wallet: Pubkey,
    pub username: String,
    pub level: u16,
    pub experience: u64,
    pub gold: u64,
    pub health: u32,
    pub mana: u32,
    pub equipped_weapon: Option<Pubkey>,
    pub equipped_armor: Option<Pubkey>,
    pub equipped_accessory: Option<Pubkey>,
    pub total_items_owned: u64,
    pub total_monsters_defeated: u64,
    pub created_at: i64,
    pub last_login: i64,
}

#[account]
pub struct GameItem {
    pub id: u64,
    pub owner: Pubkey,
    pub name: String,
    pub item_type: ItemType,
    pub rarity: Rarity,
    pub level_requirement: u16,
    pub power: u32,
    pub defense: u32,
    pub durability: u32,
    pub max_durability: u32,
    pub is_equipped: bool,
    pub is_tradeable: bool,
    pub created_at: i64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum ItemType {
    Weapon {
        damage: u32,
        attack_speed: u32,
    },
    Armor {
        defense_bonus: u32,
        health_bonus: u32,
    },
    Accessory {
        mana_bonus: u32,
        luck_bonus: u32,
    },
    Consumable {
        effect: ConsumableEffect,
        uses: u32,
    },
    Material {
        tier: u8,
    },
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum ConsumableEffect {
    HealHealth {
        amount: u32,
    },
    RestoreMana {
        amount: u32,
    },
    BoostExperience {
        percentage: u32,
        duration: i64,
    },
    IncreaseGold {
        percentage: u32,
        duration: i64,
    },
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum Rarity {
    Common,
    Uncommon,
    Rare,
    Epic,
    Legendary,
    Mythic,
}

#[account]
pub struct CraftingRecipe {
    pub id: u64,
    pub name: String,
    pub result_item_type: ItemType,
    pub result_rarity: Rarity,
    pub result_power: u32,
    pub required_level: u16,
    pub required_materials: Vec<MaterialRequirement>,
    pub crafting_cost: u64,
    pub success_rate: u8,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub struct MaterialRequirement {
    pub material_tier: u8,
    pub quantity: u32,
}

#[account]
pub struct TradeOffer {
    pub id: u64,
    pub offerer: Pubkey,
    pub offered_item: Pubkey,
    pub requested_gold: Option<u64>,
    pub requested_item_type: Option<ItemType>,
    pub requested_min_rarity: Option<Rarity>,
    pub recipient: Option<Pubkey>,
    pub status: TradeStatus,
    pub created_at: i64,
    pub expires_at: i64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum TradeStatus {
    Open,
    Accepted,
    Cancelled,
    Expired,
}

#[account]
pub struct Achievement {
    pub player: Pubkey,
    pub achievement_type: AchievementType,
    pub unlocked_at: i64,
    pub reward_claimed: bool,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum AchievementType {
    ReachLevel {
        level: u16,
    },
    DefeatMonsters {
        count: u64,
    },
    CollectItems {
        rarity: Rarity,
        count: u64,
    },
    EarnGold {
        amount: u64,
    },
    CraftItems {
        count: u64,
    },
    CompleteTrades {
        count: u64,
    },
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub struct GameEvent {
    pub event_type: EventType,
    pub player: Pubkey,
    pub timestamp: i64,
    pub block_height: u64,
}

#[derive(AnchorSerialize, AnchorDeserialize, Debug, Clone)]
pub enum EventType {
    PlayerCreated,
    ItemMinted {
        item_id: u64,
        rarity: Rarity,
    },
    ItemEquipped {
        item_id: u64,
    },
    ItemUnequipped {
        item_id: u64,
    },
    ItemCrafted {
        item_id: u64,
        recipe_id: u64,
    },
    ItemUpgraded {
        item_id: u64,
        new_power: u32,
    },
    ItemConsumed {
        item_id: u64,
        effect: ConsumableEffect,
    },
    TradeCreated {
        trade_id: u64,
    },
    TradeCompleted {
        trade_id: u64,
        partner: Pubkey,
    },
    MonsterDefeated {
        monster_type: String,
        gold_earned: u64,
        exp_earned: u64,
    },
    LevelUp {
        new_level: u16,
    },
    AchievementUnlocked {
        achievement_type: AchievementType,
    },
}

#[account]
pub struct GameStats {
    pub total_players: u64,
    pub total_items_minted: u64,
    pub total_trades_completed: u64,
    pub total_items_crafted: u64,
    pub total_gold_circulating: u64,
    pub most_valuable_item: Option<Pubkey>,
    pub highest_level_player: Option<Pubkey>,
    pub last_updated: i64,
}
